name: ci-cd

on: [push]

jobs:
  build:
    name: build & tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cache:vendor
        uses: actions/cache@v1
        id: vendor
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-

      - name: composer:install
        if: steps.vendor.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: phpunit:run
        run: vendor/bin/phpunit
